config/routes.rb
Attendance::Application.routes.draw do
  resources :assignments do
    resources :clients
  end
  resources :clients do
    resources :classifications
    get 'attendance', :on => :member
  end

  resources :sheets

  resources :classifications
  resources :schools

  get "home/index"

  root :to => "home#index"

end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  def index
    @assignments = Assignment.select('DISTINCT date').order('date DESC')
  end

  def new
    @clients = Client.where('discharge_date IS NULL').all

    @assignments = []
    @clients.each do |c| @assignments.push(Assignment.new(:client_id => c.id)) end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @assignment }
    end
  end

  def show
    @assignments = Assignment.where(:date => params[:id])
  end

  def destroy
    Assignment.where(:date => params[:id]).destroy_all

    respond_to do |format|
      format.html { redirect_to(sheets_url) }
    end
  end

  def create
    @assignments = parse(params)
    qdate = parse_date(params[:assignment])
    respond_to do |format|
      @assignments.each do |assignment|
        if assignment.save
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => assignment.errors, :status => :unprocessable_entity }
        end
      end
      format.html { redirect_to(edit_sheet_path(qdate)) }
    end
  end

  def edit
    @assignments = Assignment.where(:date => params[:id])
  end

  def update
    qdate = Date.new(params[:id].to_i)
    assignment_keys = params[:assignments].keys
    respond_to do |format|
      assignment_keys.each do |k|
        assignment = Assignment.find(k)
        if assignment.update_attributes(params[:assignments][k][:assignment])
        else
          format.js { render :json => assignment.errors, :status => :unprocessable_entity }
        end
      end
      format.js { render :status => 206 }
    end
  end

  private
  def parse(params)
    assignments = Array.new
    qdate = parse_date(params[:assignment])

    params[:assignments].values.collect { |values|
      assignments.push(Assignment.new(:client_id => values["assignment"]["client_id"],
                                      :status => values["assignment"]["status"],
                                      :date => qdate))
    }
    return assignments
  end

  private
  def parse_date(d)
    qyear = d["date(1i)"].to_i
    qmonth = d["date(2i)"].to_i
    qday = d["date(3i)"].to_i
    return Date.new(year=qyear,month=qmonth,day=qday)
  end
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/sheets/_form.html.erb
<%= form_for :assignments, :url => "/sheets" do |f| %>
  <div class="field">
    Date: <%= date_select :assignment, "date", :start_year => Time.now.year, :end_year => 1991 %>
  </div>
  <% i = 0 %>
  <% @assignments.each do |assignment| %>
    <%= f.fields_for :assignment, assignment do |aform| %>
      <% if assignment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(assignment.errors.count, "error") %> prohibited this attendance assignment from being saved:</h2>

          <ul>
          <% assignment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= aform.object.client.name %>
        <%= aform.hidden_field :client_id, :id => "assignments_#{i}_assignment_client_id", :name => "assignments[#{i}][assignment][client_id]" %>
        <%= aform.select "status", ["Present", "Tardy", "Unexcused Absence", "Excused Absence", "School Closed", "Suspended"], { :include_blank => true }, { :id => "assignments_#{i}_assignment_status", :name => "assignments[#{i}][assignment][status]" } %>
        <% i += 1 %>
      </div>
    <% end %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sheets/edit.html.erb
<% require 'lib/attendance_status_values' %>
<h2 class="ui-widget-header" style="padding:10px;">Editing Attendance Sheet</h2>
<div class="ui-widget ui-widget-content">
<%= form_tag("/sheets/#{params[:id]}", :remote => true, :method => :put, :id => "edit_assignments_with_date_#{params[:id]}") do %>
  <% if @assignments.any? %>
    <div class="field">
      <div class="large">Date: <%= @assignments[0].date %></div>
    </div>
  <% end %>
  <% @assignments.each do |assignment| %>
    <%= hidden_field_tag "assignments[#{assignment.id}][assignment][date]", value = assignment.date %>
    <%= hidden_field_tag "assignments[#{assignment.id}][assignment][client_id]", value = assignment.client.id %>
    <div class="field">
      <span style="width:150px;float:left;margin-top:2px;"><%= assignment.client.name %></span>
      <span class="status_buttonset">
        <% AttendanceStatusValues::VALUES.each do |s| %>
          <%= label_tag "assignments_#{assignment.id}_assignment_status_#{s.sub(' ', '_')}", s %>
          <%= radio_button_tag id = "assignments_#{assignment.id}_assignment_status", s, check = s.eql?( assignment.status), { :name => "assignments[#{assignment.id}][assignment][status]" } %>
        <% end %>
      </span>
    </div>
  <% end %>
  <div class="actions">
    <%= submit_tag value = "Update sheet" %><span id="last_updated"></span>
  </div>
<% end %>
</div>
<br />
<%= link_to 'Back', sheets_path %>

app/views/sheets/index.html.erb
<h2 class="ui-widget-header" style="padding:10px;">Listing Attendance Sheets</h2>
<table class="ui-widget ui-widget-content">
  <tr class="ui-widget-header">
    <th>Date</th>
    <th>Action</th>
  </tr>
  <% @assignments.each do |a| %>
    <tr>
      <td><%= a.date %></td>
      <td><%= link_to 'Show', sheet_path(a.date) %> |
          <%= link_to 'Edit', edit_sheet_path(a.date) %> |
          <%= link_to 'Destroy', sheet_path(a.date), :confirm => "Are you sure?", :method => :delete %>
      </td>
    </tr>
  <% end %>
</table>
<%= link_to 'Back', root_path %>

app/views/sheets/new.html.erb
<% require 'lib/attendance_status_values' %>
<h2 class="ui-widget-header" style="padding:10px;">New Attendance Sheet</h2>
<div class="ui-widget ui-widget-content">
<%= form_for :assignments, :url => "/sheets" do |f| %>
  <div class="field">
    <div class="large">Date: <%= date_select :assignment, "date", :start_year => Time.now.year, :end_year => 1991 %></div>
  </div>
  <% i = 0 %>
  <% @assignments.each do |assignment| %>
    <%= f.fields_for :assignment, assignment do |aform| %>
      <% if assignment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(assignment.errors.count, "error") %> prohibited this attendance assignment from being saved:</h2>

          <ul>
          <% assignment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= aform.hidden_field :client_id, :id => "assignments_#{i}_assignment_client_id", :name => "assignments[#{i}][assignment][client_id]" %>

      <div class="field">
        <span style="width:150px;float:left;margin-top:2px;"><%= aform.object.client.name %></span>
        <span class="status_buttonset">
          <% AttendanceStatusValues::VALUES.each do |s| %>
            <%= aform.label s, { :for => "assignments_#{i}_assignment_status_#{s.sub(' ', '_')}" } %>
            <%= aform.radio_button "status", s, { :id => "assignments_#{i}_assignment_status_#{s.sub(' ','_')}", :name => "assignments[#{i}][assignment][status]" } %>
          <% end %>
        </span>
      </div>
      <% i += 1 %>
    <% end %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
<br />
<%= link_to 'Back', '/' %>

app/views/sheets/show.html.erb
<h2 class="ui-widget-header" style="padding:10px;">Listing Attendance Assignments</h2>

<table class="ui-widget ui-widget-content">
  <tr class="ui-widget-header">
    <th>Attendance Sheet</th>
    <th>Client</th>
    <th>Status</th>
    <th>Actions</th>
  </tr>

<% @assignments.each do |assignment| %>
  <tr>
    <td><%= assignment.date %></td>
    <td><%= assignment.client.name %></td>
    <td><%= assignment.status %></td>
    <td><%= link_to 'Show', assignment %> |
      <%= link_to 'Edit', edit_assignment_path(assignment) %> |
      <%= link_to 'Destroy', assignment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attendance Sheet', new_sheet_path %> |
<%= link_to 'Back', sheets_path %>

app/views/sheets/update.js.erb
$("#last_updated")
    .html('<img src="/stylesheets/blueprint/plugins/buttons/icons/tick.png" alt=""/>')
    .show()
    .fadeOut(4000);