config/routes.rb
Attendance::Application.routes.draw do
  resources :assignments do
    resources :clients
  end
  resources :clients do
    resources :classifications
    get 'attendance', :on => :member
  end

  resources :sheets

  resources :classifications
  resources :schools

  get "home/index"

  root :to => "home#index"

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :assignments
  belongs_to :school
  belongs_to :classification
  accepts_nested_attributes_for :assignments
  validates_presence_of :name
  validates_uniqueness_of :name,
                          :message => "has already been used",
                          :case_sensitive => false
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :authenticate, :except => [:index, :show]
  # GET /clients
  # GET /clients.xml
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.xml
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.xml
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.xml
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to(@client, :notice => 'Client was successfully created.') }
        format.xml  { render :xml => @client, :status => :created, :location => @client }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @client.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /clients/1/attendance
  # GET /clients/1/attendance.xml
  def attendance
    @assignments = Assignment.order('date DESC').where(:client_id => params[:id])

    respond_to do |format|
      format.html # attendance.html.erb
      format.xml  { render :xml => @assignments }
    end
  end

  # PUT /clients/1
  # PUT /clients/1.xml
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to(@client, :notice => 'Client was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @client.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.xml
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to(clients_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<%= form.fields_for :clients do |client_form| %>
  <div class="field">
    Name<%= client_form.text_field :name, :disabled => true %>
    <%= render :partial => "sheets/assignments",
               :locals  => { :form => client_form } %>
  </div>
<% end %>

app/views/clients/_form.html.erb
<%= form_for(@client) do |client_form| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= client_form.label :name %><br />
    <%= client_form.text_field :name, :class => "text" %>
  </div>
  <div class="field">
    <%= client_form.label :school_id %><br />
    <%= client_form.select :school_id, School.order('name asc').all.collect { |c| [ c.name, c.id ] }, { :include_blank => true } %>
  </div>
  <div class="field">
    <%= client_form.label :admission_date%><br />
    <%= client_form.date_select :admission_date, :include_blank => true, :start_year => Time.now.year, :end_year => 1991 %>
  </div>
  <div class="field">
    <%= client_form.label :discharge_date %><br />
    <%= client_form.date_select :discharge_date, :include_blank => true, :start_year => Time.now.year, :end_year => 1991 %>
  </div>
  <div class="field">
    <%= client_form.label :iep_date %><br />
    <%= client_form.date_select :iep_date, :include_blank => true, :start_year => Time.now.year, :end_year => 1991 %>
  </div>
  <div class="field">
    <%= client_form.label :classification_id, "Billing Classification" %><br />
    <%= client_form.select :classification_id, Classification.all.collect { |c| [ c.display_name, c.id ] }, { :include_blank => true } %>
  </div>
  <div class="actions">
    <%= client_form.submit %>
  </div>
<% end %>

app/views/clients/attendance.html.erb
<h2 class="ui-widget-header" style="padding:10px;">Attendance Report</h2>

<table class="ui-widget ui-widget-content">
  <tr class="ui-widget-header">
    <th>Date</th>
    <th>Name</th>
    <th>Status</th>
  </tr>

<% @assignments.each do |assignment| %>
  <tr>
    <td><%= assignment.date %></td>
    <td><%= assignment.client.name %></td>
    <td><%= assignment.status %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Back', clients_path %>

app/views/clients/edit.html.erb
<h2 class="ui-widget-header" style="padding:10px;">Editing Client</h2>
<div class="ui-widget-content">
<%= render 'form' %>
</div>
<br />
<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h2 class="ui-widget-header" style="padding:10px;">Listing Clients</h2>

<table class="ui-widget ui-widget-content">
  <tr class="ui-widget-header">
    <th>Name</th>
    <th>Previous School</th>
    <th>Admission Date</th>
    <th>Actions</th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.name %></td>
    <td><%= client.school.name unless client.school == nil %></td>
    <td><%= client.admission_date %></td>
    <td><%= link_to 'Show', client %> |
      <%= link_to 'Attendance', attendance_client_path(client) %> |
      <%= link_to 'Edit', edit_client_path(client) %> |
      <%= link_to 'Destroy', client, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %> |
<%= link_to 'Back', '/' %>

app/views/clients/new.html.erb
<h2 class="ui-widget-header" style="padding:10px;">New Client</h2>
<div class="ui-widget ui-widget-content">
<%= render 'form' %>
</div>
<br />
<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<% if !notice.nil? then %>
<p id="notice"><%= notice %></p>
<% end %>

<table class="ui-widget ui-widget-content">
  <tr class="ui-widget-header">
    <th colspan="2"><%= @client.name %></th>
  </tr>
  <tr>
    <td><b>Previous School:</b></td>
    <td><%= @client.school.name unless @client.school == nil %></td>
  </tr>
  <tr>
    <td><b>Admission Date:</b></td>
    <td><%= @client.admission_date %></td>
  </tr>
  <tr>
    <td><b>IEP Date:</b></td>
    <td><%= @client.iep_date %></td>
  </tr>
  <tr>
    <td><b>Discharge Date:</b></td>
    <td><%= @client.discharge_date %></td>
  </tr>
  <tr>
    <td><b>Billing Classification:</b></td>
    <td><%= @client.classification.display_name unless @client.classification == nil %></td>
  </tr>
</table>

<%= link_to 'Attendance', attendance_client_path(@client) %> |
<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>