config/routes.rb
Attendance::Application.routes.draw do
  resources :assignments do
    resources :clients
  end
  resources :clients do
    resources :classifications
    get 'attendance', :on => :member
  end

  resources :sheets

  resources :classifications
  resources :schools

  get "home/index"

  root :to => "home#index"

end

app/models/classification.rb
class Classification < ActiveRecord::Base
  has_many :clients
  validates_presence_of :display_name, :name, :rate
  validates_numericality_of :rate, :greater_than => 0
end

app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController
  before_filter :authenticate, :except => [:index, :show]
  # GET /classifications
  # GET /classifications.xml
  def index
    @classifications = Classification.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @classifications }
    end
  end

  # GET /classifications/1
  # GET /classifications/1.xml
  def show
    @classification = Classification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @classification }
    end
  end

  # GET /classifications/new
  # GET /classifications/new.xml
  def new
    @classification = Classification.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @classification }
    end
  end

  # GET /classifications/1/edit
  def edit
    @classification = Classification.find(params[:id])
  end

  # POST /classifications
  # POST /classifications.xml
  def create
    @classification = Classification.new(params[:classification])

    respond_to do |format|
      if @classification.save
        format.html { redirect_to(@classification, :notice => 'Classification was successfully created.') }
        format.xml  { render :xml => @classification, :status => :created, :location => @classification }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @classification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /classifications/1
  # PUT /classifications/1.xml
  def update
    @classification = Classification.find(params[:id])

    respond_to do |format|
      if @classification.update_attributes(params[:classification])
        format.html { redirect_to(@classification, :notice => 'Classification was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @classification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /classifications/1
  # DELETE /classifications/1.xml
  def destroy
    @classification = Classification.find(params[:id])
    @classification.destroy

    respond_to do |format|
      format.html { redirect_to(classifications_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/classifications_helper.rb
module ClassificationsHelper
end

app/views/classifications/_form.html.erb
<%= form_for(@classification) do |f| %>
  <% if @classification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classification.errors.count, "error") %> prohibited this classification from being saved:</h2>

      <ul>
      <% @classification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :display_name %><br />
    <%= f.text_field :display_name, :class => 'text' %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :class => 'text' %>
  </div>
  <div class="field">
    <%= f.label :rate %><br />
    <%= f.number_field :rate, :step => 0.01, :class => 'text' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classifications/edit.html.erb
<h2 class="ui-widget-header" style="padding:10px;">Editing classification</h2>
<div class="ui-widget ui-widget-content">
<%= render 'form' %>
</div>
<br />
<%= link_to 'Show', @classification %> |
<%= link_to 'Back', classifications_path %>

app/views/classifications/index.html.erb
<h2 class="ui-widget-header" style="padding:10px;">Listing classifications</h2>

<table class="ui-widget ui-widget-content">
  <tr class="ui-widget-header">
    <th>Display name</th>
    <th>Name</th>
    <th>Rate</th>
    <th>Action</th>
  </tr>

<% @classifications.each do |classification| %>
  <tr>
    <td><%= classification.display_name %></td>
    <td><%= classification.name %></td>
    <td><%= number_to_currency classification.rate %></td>
    <td><%= link_to 'Show', classification %> |
        <%= link_to 'Edit', edit_classification_path(classification) %> |
        <%= link_to 'Destroy', classification, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Classification', new_classification_path %> |
<%= link_to 'Back', '/' %>

app/views/classifications/new.html.erb
<h2 class="ui-widget-header" style="padding:10px;">New classification</h2>
<div class="ui-widget ui-widget-content">
<%= render 'form' %>
</div>
<br />
<%= link_to 'Back', classifications_path %>

app/views/classifications/show.html.erb
<% if !notice.nil? then %>
<p id="notice"><%= notice %></p>
<% end %>

<table class="ui-widget ui-widget-content">
  <tr>
    <th colspan="2" class="ui-widget-header">
      <%= @classification.display_name %>
    </th>
  </tr>
  <tr>
    <td>Name</td>
    <td><%= @classification.name %></td>
  </tr>
  <tr>
    <td>Rate</td>
    <td><%= number_to_currency @classification.rate %></td>
  </tr>
</table>

<%= link_to 'Edit', edit_classification_path(@classification) %> |
<%= link_to 'Back', classifications_path %>