config/routes.rb
Attendance::Application.routes.draw do
  resources :assignments do
    resources :clients
  end
  resources :clients do
    resources :classifications
    get 'attendance', :on => :member
  end

  resources :sheets

  resources :classifications
  resources :schools

  get "home/index"

  root :to => "home#index"

end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :clients
  validates_presence_of :name
  validates_uniqueness_of :name,
                          :message => "has already been used",
                          :case_sensitive => false
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  # GET /schools
  # GET /schools.xml
  def index
    @schools = School.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.xml
  def show
    @school = School.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.xml
  def new
    @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
  end

  # POST /schools
  # POST /schools.xml
  def create
    @school = School.new(params[:school])

    respond_to do |format|
      if @school.save
        format.html { redirect_to(@school, :notice => 'School was successfully created.') }
        format.xml  { render :xml => @school, :status => :created, :location => @school }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @school.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.xml
  def update
    @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to(@school, :notice => 'School was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @school.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.xml
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to(schools_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :class => 'text' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h2 class="ui-widget-header" style="padding:10px;">Editing school</h2>
<div class="ui-widget ui-widget-content">
<%= render 'form' %>
</div>
<br />
<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h2 class="ui-widget-header" style="padding:10px;">Listing schools</h2>

<table class="ui-widget ui-widget-content">
  <tr class="ui-widget-header">
    <th>Name</th>
    <th>Action</th>
  </tr>

<% @schools.each do |school| %>
  <tr>
    <td><%= school.name %></td>
    <td><%= link_to 'Show', school %> |
        <%= link_to 'Edit', edit_school_path(school) %> |
        <%= link_to 'Destroy', school, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New School', new_school_path %> |
<%= link_to 'Back', '/' %>

app/views/schools/new.html.erb
<h2 class="ui-widget-header" style="padding:10px;">New school</h2>
<div class="ui-widget ui-widget-content">
<%= render 'form' %>
</div>
<br />
<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<% if !notice.nil? then %>
<p id="notice"><%= notice %></p>
<% end %>

<table class="ui-widget ui-widget-content">
  <tr class="ui-widget-header">
    <td>Name</td>
  </tr>
  <tr>
    <td><%= @school.name %></td>
  </tr>
</table>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>